config/routes.rb
Rails.application.routes.draw do
  resources :audit_logs
  namespace :admin do
    resources :users
    resources :posts
    resources :admin_users

    root to: "users#index"
  end

  resources :posts
  devise_for :users, skip: [:registrations]
  root to: 'static#homepage'
end

app/models/admin_user.rb
class AdminUser < User
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/audit_log.rb
class AuditLog < ApplicationRecord
  belongs_to :user
end

app/models/post.rb
class Post < ApplicationRecord
  enum status: { submitted: 0, approved: 1, rejected: 2 }
  belongs_to :user, optional: true
  validates_presence_of :date, :rationale, :overtime_request
  validates :overtime_request, numericality: { greater_than: 0.0 }

  scope :posts_by, ->(user) {
    where(user_id: user.id)
  }
end

app/models/user.rb
class User < ApplicationRecord
  has_many :posts
  has_many :audit_logs
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates_presence_of :first_name, :last_name, :phone

  PHONE_REGEX = /\+?[1-9]\d{1,14}/

  validates_format_of :phone, with: PHONE_REGEX

  def full_name
    last_name.upcase + ", " + first_name.upcase
  end
end

app/controllers/admin/admin_users_controller.rb
module Admin
  class AdminUsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = AdminUser.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   AdminUser.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  def self.admin_types
    ['AdminUser']
  end

  class ApplicationController < Administrate::ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_admin

    def authenticate_admin
      unless Admin.admin_types.include?(current_user.try(:type))
        flash[:alert] = "You are not authorized to access this page."
        redirect_to(root_path)
      end
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/posts_controller.rb
module Admin
  class PostsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Post.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Post.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pundit
  protect_from_forgery with: :exception
  before_action :authenticate_user!

  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

  private

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    redirect_to(root_path)
  end
end

app/controllers/audit_logs_controller.rb
class AuditLogsController < ApplicationController
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.posts_by current_user
  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id
    
    if @post.save
      redirect_to @post, notice: 'Your post was created successfully'
    else
      render :new
    end
  end

  def edit
    authorize @post
  end

  def update
    authorize @post

    if @post.update(post_params)
      redirect_to @post, notice: 'Your post was updated successfully'
    else
      render :edit
    end
  end

  def show
  end

  def destroy
    @post.delete
    
    redirect_to posts_path, notice: 'Your post was deleted successfully'
  end

  private

    def post_params
      params.require(:post).permit(:date, :rationale, :status, :overtime_request)
    end

    def set_post
      @post = Post.find(params[:id])
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
  def homepage
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def active?(path)
    "active" if current_page?(path)
  end
end

app/helpers/audit_logs_helper.rb
module AuditLogsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
  def status_label status
    status_span_generator status
  end

  private

    def status_span_generator status
      case status
      when 'submitted'
        content_tag(:span, status.titleize, class: 'label label-primary')
      when 'approved'
        content_tag(:span, status.titleize, class: 'label label-success')  
      when 'rejected'
        content_tag(:span, status.titleize, class: 'label label-danger')
      end
    end
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Overtime
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag    'posts', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
  .container
    .row
      .col-md-12
        = render 'shared/nav'
        = yield
  
  = render 'shared/alerts'

app/views/posts/_form.html.haml
%form.form-horizontal{:role => "form"}
  - if @post.errors.any?
    - @post.errors.full_messages.each do |msg|
      = js add_gritter(msg, title: "Overtime App Notification", sticky: false, time: 3000, image: :notice)

  .form-group
    = label :post, :overtime_request, 'Overtime Request', :class => 'col-sm-2 control-label'
    .col-sm-10
      = text_field :post, :overtime_request, :class => 'form-control'
  .form-group
    = label :post, :date, 'Date', :class => 'col-sm-2 control-label'
    .col-sm-10
      = date_field :post, :date, :class => 'form-control'
  .form-group
    = label :post, :rationale, 'Rationale', :class => 'col-sm-2 control-label'
    .col-sm-10
      = text_area :post, :rationale, :class => 'form-control'
  = render 'status' if current_user.type == 'AdminUser'
  .form-group
    .col-sm-offset-2.col-sm-10
      = submit_tag('Save', :class => 'btn btn-primary btn-block')

app/views/posts/_post.html.haml
%tr
  %td
    = post.id
  %td
    = post.overtime_request
  %td
    = post.date
  %td
    = post.user.full_name
  %td
    = link_to truncate(post.rationale), post
  %td
    = status_label(post.status)
  %td
    = link_to '', edit_post_path(post), :id => "edit_#{post.id}", :class => 'glyphicon glyphicon-pencil index-icons' if policy(post).update?
  %td
    = link_to '', post_path(post), method: :delete, :id => "delete_#{post.id}", :class => 'glyphicon glyphicon-trash index-icons', data: { confirm: 'Are you sure?' }    

app/views/posts/_status.html.haml
.form-group
  .col-sm-offset-2.col-sm-10
    = radio_button :post, :status, 'submitted'
    = label :post, :status, 'Submitted', :class => 'control-label'
    = radio_button :post, :status, 'approved'
    = label :post, :status, 'Approved', :class => 'control-label'
    = radio_button :post, :status, 'rejected'
    = label :post, :status, 'Rejected', :class => 'control-label'   

app/views/posts/edit.html.haml
%h2 Edit

= form_tag post_path(@post), method: :put do
  = render "form"

app/views/posts/index.html.haml
%h2 Posts

%table.table.table-striped.table-hover
  %thead
    %tr
      %th #
      %th Overtime Request
      %th Date
      %th User
      %th Rationale
      %th Status
  %tbody
    = render @posts

app/views/posts/new.html.haml
%h2 New

= form_tag posts_path do
  = render "form"

app/views/posts/show.html.haml
%h2 
  = @post.rationale
.well
  %h3
    Overtime Amount Requested:
    = @post.overtime_request
  %h3
    Employee:
    = @post.user.full_name
  %h3
    Date:
    = @post.date
  %h3
    Status:
    = @post.status

= link_to 'Edit', edit_post_path(@post), :class => 'btn btn-primary' if policy(@post).update?

app/views/shared/_alerts.html.haml
- if flash[:alert]
  = js add_gritter(flash[:alert], title: "Overtime App Alert", sticky: false, time: 1500, image: :warning)
- elsif flash[:notice]
  = js add_gritter(flash[:notice], title: "Overtime App Notification", sticky: false, time: 1500, image: :notice)
- else
  = js add_gritter(flash[:error], title: "Overtime App Error", sticky: false, time: 1500, image: :error)

app/views/shared/_nav.html.haml
- if current_user
  %div.logo
    %h1 Time Tracker

  %ul.nav.nav-tabs.custom-nav
    %li{:class => active?(root_path)}
      =link_to "Home", root_path
    %li{:class => active?(posts_path)}
      =link_to "Time Entries", posts_path
    %li{:class => active?(new_post_path)}
      =link_to "Add New Entry", new_post_path, :id => 'new_post_from_nav'
    %li.dropdown.pull-right
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        Options
        %strong.caret
      %ul.dropdown-menu
        - if current_user.try(:type) == 'AdminUser'
          %li
            =link_to "Admin Dashboard", admin_root_path
          %li.divider
        %li
          =link_to "Logout", destroy_user_session_path, method: :delete